/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz.UI;

import quiz.BO.Services.VraagServices;
import quiz.BO.Vraag;

/**
 *
 * @author yuri
 */
public class NieuweVraag extends javax.swing.JFrame {

    VraagServices service = new VraagServices();
    /**
     * Creates new form NieuweVraag
     */
    public NieuweVraag() {
        initComponents();
        
        lstVragen.setListData(service.getAllVragen().toArray());
        
        panelMultiplechoice.setVisible(false);
        panelMedia.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox();
        btnToevoegen = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtVraag = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAntwoord = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbCategorie = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstVragen = new javax.swing.JList();
        panelMultiplechoice = new javax.swing.JPanel();
        txtKeuzeA = new javax.swing.JTextField();
        txtKeuzeC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtKeuzeB = new javax.swing.JTextField();
        txtKeuzeD = new javax.swing.JTextField();
        panelMedia = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtMediaLocatie = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Vraag toevoegen van het type: ");

        cmbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normaal", "Multiplechoice", "Foto" }));
        cmbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTypeActionPerformed(evt);
            }
        });

        btnToevoegen.setText("Toevoegen");
        btnToevoegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToevoegenActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel2.setText("Stel hier uw vraag:");

        jLabel3.setText("Antwoord:");

        jLabel6.setText("Categorie:");

        cmbCategorie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "General Knowledge", "Sports", "Music", "TV", "Geography" }));

        lstVragen.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstVragen.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstVragenValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstVragen);

        txtKeuzeA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeuzeAActionPerformed(evt);
            }
        });

        txtKeuzeC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeuzeCActionPerformed(evt);
            }
        });

        jLabel4.setText("Multiple choice keuzes (1 moet het antwoord zijn):");

        javax.swing.GroupLayout panelMultiplechoiceLayout = new javax.swing.GroupLayout(panelMultiplechoice);
        panelMultiplechoice.setLayout(panelMultiplechoiceLayout);
        panelMultiplechoiceLayout.setHorizontalGroup(
            panelMultiplechoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMultiplechoiceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMultiplechoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMultiplechoiceLayout.createSequentialGroup()
                        .addComponent(txtKeuzeA, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtKeuzeC, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelMultiplechoiceLayout.createSequentialGroup()
                        .addComponent(txtKeuzeB, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtKeuzeD, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMultiplechoiceLayout.setVerticalGroup(
            panelMultiplechoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMultiplechoiceLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMultiplechoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKeuzeA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKeuzeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMultiplechoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKeuzeB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKeuzeD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Media locatie:");

        javax.swing.GroupLayout panelMediaLayout = new javax.swing.GroupLayout(panelMedia);
        panelMedia.setLayout(panelMediaLayout);
        panelMediaLayout.setHorizontalGroup(
            panelMediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMediaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMediaLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 157, Short.MAX_VALUE))
                    .addComponent(txtMediaLocatie))
                .addContainerGap())
        );
        panelMediaLayout.setVerticalGroup(
            panelMediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMediaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtMediaLocatie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbType, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnToevoegen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVraag)
                    .addComponent(txtAntwoord)
                    .addComponent(panelMultiplechoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVraag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnToevoegen)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(txtAntwoord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelMultiplechoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnToevoegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToevoegenActionPerformed
        Vraag v = new Vraag();
        v.setMoeilijkheidsgraad(49);
        v.setVraag(txtVraag.getText());
        v.setAntwoord(txtAntwoord.getText());
        v.setCategorie(cmbCategorie.getSelectedItem().toString());
        v.setType(cmbType.getSelectedItem().toString());
        
        if(cmbType.getSelectedIndex() == 1)
        {
            v.setExtraInfo(txtKeuzeA.getText() + ";" + txtKeuzeB.getText() + ";" + txtKeuzeC.getText() + ";" + txtKeuzeD.getText() + ";");
        }
        else if(cmbType.getSelectedIndex() == 2 || cmbType.getSelectedIndex() == 3)
        {
            v.setMedia(txtMediaLocatie.getText());
        }
            
        service.SaveVraag(v);
            
        lstVragen.setListData(service.getAllVragen().toArray());
    }//GEN-LAST:event_btnToevoegenActionPerformed

    private void cmbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypeActionPerformed
        if(cmbType.getSelectedIndex() == 1)
        {
            panelMultiplechoice.setVisible(true);
        }
        else if(cmbType.getSelectedIndex() == 2)
        {
            panelMultiplechoice.setVisible(false);
            panelMedia.setVisible(true);
        }
        else if(cmbType.getSelectedIndex() == 3)
        {
            panelMultiplechoice.setVisible(false);
            panelMedia.setVisible(true);
        }
        else
        {
            panelMultiplechoice.setVisible(false);
            panelMedia.setVisible(false);
        }
    }//GEN-LAST:event_cmbTypeActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        Vraag v = (Vraag) lstVragen.getSelectedValue();
        
        v.setVraag(txtVraag.getText());
        v.setAntwoord(txtAntwoord.getText());
        v.setCategorie(cmbCategorie.getSelectedItem().toString());
        v.setType(cmbType.getSelectedItem().toString());
        
        if(cmbType.getSelectedIndex() == 1)
        {
            v.setExtraInfo(txtKeuzeA.getText() + ";" + txtKeuzeB.getText() + ";" + txtKeuzeC.getText() + ";" + txtKeuzeD.getText() + ";");
        }
        else if(cmbType.getSelectedIndex() == 2 || cmbType.getSelectedIndex() == 3)
        {
            v.setMedia(txtMediaLocatie.getText());
        }
            
        service.UpdateVraag(v.getID(),v);
            
        lstVragen.setListData(service.getAllVragen().toArray());
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void lstVragenValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstVragenValueChanged
       Vraag v = (Vraag) lstVragen.getSelectedValue();
        
        if (v != null) 
        {
            txtVraag.setText(v.getVraag());
            txtAntwoord.setText(v.getAntwoord());
            txtMediaLocatie.setText(v.getMedia());
            
            if(v.getType().equalsIgnoreCase("Normaal")){cmbType.setSelectedIndex(0);}
            else if(v.getType().equalsIgnoreCase("Multiple choice"))
            {
                cmbType.setSelectedIndex(1);
                
                String string = v.getExtraInfo();
                String[] parts = string.split(";");
                txtKeuzeA.setText(parts[0]);
                txtKeuzeB.setText(parts[1]);
                txtKeuzeC.setText(parts[2]);
                txtKeuzeD.setText(parts[3]);
            }
            else if(v.getType().equalsIgnoreCase("Foto vraag")){cmbType.setSelectedIndex(2);}
            else if(v.getType().equalsIgnoreCase("Fragment")){cmbType.setSelectedIndex(3);}
            
            
            if(v.getCategorie().equalsIgnoreCase("Sport")){cmbCategorie.setSelectedIndex(0);}
            else if(v.getCategorie().equalsIgnoreCase("Politiek")){cmbCategorie.setSelectedIndex(1);}
        }
    }//GEN-LAST:event_lstVragenValueChanged

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        Vraag v = (Vraag) lstVragen.getSelectedValue();
        
        service.DeleteVraag(v.getID(),v);
            
        lstVragen.setListData(service.getAllVragen().toArray());
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtKeuzeAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeuzeAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeuzeAActionPerformed

    private void txtKeuzeCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeuzeCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeuzeCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NieuweVraag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NieuweVraag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NieuweVraag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NieuweVraag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NieuweVraag().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnToevoegen;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cmbCategorie;
    private javax.swing.JComboBox cmbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstVragen;
    private javax.swing.JPanel panelMedia;
    private javax.swing.JPanel panelMultiplechoice;
    private javax.swing.JTextField txtAntwoord;
    private javax.swing.JTextField txtKeuzeA;
    private javax.swing.JTextField txtKeuzeB;
    private javax.swing.JTextField txtKeuzeC;
    private javax.swing.JTextField txtKeuzeD;
    private javax.swing.JTextField txtMediaLocatie;
    private javax.swing.JTextField txtVraag;
    // End of variables declaration//GEN-END:variables
}
